version: '3.7'

services:
  pgsql:
    image: postgres
    container_name: 'pgsql'
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    env_file: 
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - TYPEORM_USERNAME=$TYPEORM_USERNAME
      - TYPEORM_PASSWORD=$TYPEORM_PASSWORD
      - TYPEORM_DATABASE=$TYPEORM_DATABASE
    ports:
      - '5432:5432'

volumes:
  db: