version: '3.7'

services:
  api:
    build: .
    image: nest
    container_name: api
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - api-logs:/usr/src/node-api/logs:rw
    environment:
      - NODE_ENV=development
    depends_on:
      - pgsql
  pgsql:
    image: postgres
    container_name: 'pgsql'
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    env_file: 
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - TYPEORM_USERNAME=$TYPEORM_USERNAME
      - TYPEORM_PASSWORD=$TYPEORM_PASSWORD
      - TYPEORM_DATABASE=$TYPEORM_DATABASE
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"

volumes:
  api-logs:
  db: