version: '3.7'

services:
  pgsql:
    image: postgres
    ports:
      - '5432:5432'
    container_name: 'pgsql'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file: 
      - .env
    environment:
      - POSTGRES_USER=$TYPEORM_USERNAME
      - POSTGRES_PASSWORD=$TYPEORM_PASSWORD

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"

volumes:
  pg-data: