name: Continuous Integration Testing

on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'build/ci-cd'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'build/ci-cd'
  schedule:
    - cron: '0 0 * * *'

jobs:
  initialization:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm i
      - name: create env file
        run: cp .env.example .env
      - name: run docker-compose
        run: docker-compose up -d
