name: Continuous Integration Testing

on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'build/ci-cd'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'build/ci-cd'
  schedule:
    - cron: '0 0 * * *'

jobs:
  initialization:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: install cross-env
        run: npm install cross-env -D

      - name: copy env development
        run: touch .env && cp .env.example .env

      - name: run docker-compose
        run: npm run testdocker
